from . import start
from . import help
from . import admin
from . import ntarmoq
from . import instagram
from . import idSend
from . import balance
from . import ichtmoyitarmoq
from . import Instagram1
from . import Instagram2
from . import Instagram3
from . import Instagram4
from . import Instagram5
from . import Instagram6
from . import instaP
from . import instaPS
from . import instaPtr1
from . import instaPS1
from . import Likeu
from . import likeu1
from . import VK
from . import VK1
from . import VK2
from . import TG
from . import TG1
from . import TG2
from . import TG3
from . import TG4
from . import TG5
from . import LEH
from . import LEH1
from . import LEH2
from . import TVR
from . import TKh
from . import TKh1
from . import TKh2
from . import TKh3
from . import TKh4
from . import TKh5
from . import YEh
from . import YEh1
from . import YEh2
from . import YEh3
from . import api_balansi
from . import Payment
from . import Kursr
