from aiogram.dispatcher.filters.state import StatesGroup, State


class Instas(StatesGroup):
    inst = State()
    userl = State()
    confin = State()
    inst1 = State()
    userl1 = State()
    confin1 = State()
    inst2 = State()
    userl2 = State()
    confin2 = State()
    inst3 = State()
    userl3 = State()
    confin3 = State()
    inst4 = State()
    userl4 = State()
    confin4 = State()
    inst5 = State()
    userl5 = State()
    confin5 = State()
    inst6 = State()
    userl6 = State()
    confin6 = State()
    #Prosmotr stete
    instaPrsi = State()
    instaPrsl = State()
    instapCon = State()
    instaPrsi1 = State()
    instaPrsl1 = State()
    instapCon1 = State()
    instaPrsi2 = State()
    instaPrsl2 = State()
    instapCon2 = State()
    instaPrsi3 = State()
    instaPrsl3 = State()
    instapCon3 = State()
    #Like state
    Likk = State()
    Likkl = State()
    Likkc = State()
    Likk1 = State()
    Likkl1 = State()
    Likkc1 = State()
    #VKONTAKT STETE
    vkin = State()
    vklink = State()
    vkcon  = State()
    vkin1 = State()
    vklink1 = State()
    vkcon1 = State()
    vkin2 = State()
    vklink2 = State()
    vkcon2 = State()
    #Telegram stet
    tgint = State()
    tglink = State()
    tgcon = State()
    tgint1 = State()
    tglink1 = State()
    tgcon1 = State()
    tgint2 = State()
    tglink2 = State()
    tgcon2 = State()
    tgint3 = State()
    tglink3 = State()
    tgcon3 = State()
    tgint4 = State()
    tglink4 = State()
    tgcon4 = State()
    tgint5 = State()
    tglink5 = State()
    tgcon5 = State()
    #likee
    leint = State()
    LElikn = State()
    lecon = State()
    leint1 = State()
    LElikn1 = State()
    lecon1 = State()
    leint2 = State()
    LElikn2 = State()
    lecon2 = State()
    #Twitter
    trint = State()
    trlink = State()
    trcon = State()
    #TikTok
    tkint = State()
    tklink = State()
    tkcon = State()
    tkint1 = State()
    tklink1 = State()
    tkcon1 = State()
    tkint2 = State()
    tklink2 = State()
    tkcon2 = State()
    tkint3 = State()
    tklink3 = State()
    tkcon3 = State()
    tkint4 = State()
    tklink4 = State()
    tkcon4 = State()
    tkint5 = State()
    tklink5 = State()
    tkcon5 = State()
    #YouTube
    yeint = State()
    yelink = State()
    yecon = State()
    yeint1 = State()
    yelink1 = State()
    yecon1 = State()
    yeint2 = State()
    yelink2 = State()
    yecon2 = State()
    yeint3 = State()
    yelink3= State()
    yecon3 = State()